# cmd: conda build . --python 2 -c pacchem -c conda-forge -c openbabel
package:
    name: automechanic
    version: "0.1.1"

source:
    path: .

requirements:
    build:
        - python=2
    run:
        - python
        - numpy
        - pandas
        - matplotlib
        - networkx
        - pyyaml
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - rdkit::rdkit
        - openbabel::openbabel
        - conda-forge::xorg-libxrender
        - pacchem::x2z
