# cmd: conda build . --python 2 -c pacchem -c conda-forge -c openbabel
package:
    name: automechanic
    version: 0.1.0

source:
    path: .

requirements:
    build:
        - python=2
    run:
        - numpy
        - pandas
        - matplotlib
        - networkx
        - pytest
        - pytest-cov
        - future
        - flake8
        - pylint
        - openbabel::openbabel
        - conda-forge::xorg-libxrender
        - pacchem::x2z
        - pacchem::inchipy
