version: 2
jobs:
    build-ubuntu:
        docker:
            - image: circleci/buildpack-deps:18.04
        steps:
            - checkout
            - run: 
                name: Create conda environments
                command: |
                    echo 'export CONDA=$HOME/miniconda' >> $BASH_ENV
                    echo 'export PATH=$CONDA/bin:$PATH' >> $BASH_ENV
                    source $BASH_ENV
                    cd install
                    ./conda.sh
                    ./amenv3.sh
                    ./amenv2.sh
            - run:
                name: Run tests with python3
                command: |
                    source activate amenv3
                    pip install .
                    cd tests/
                    pytest -v --cov=automechanic .
                    flake8 --exit-zero automechanic
                    pylint --rcfile=../.pylintrc automechanic
            - run:
                name: Run tests with python2
                command: |
                    source activate amenv2
                    pip install .
                    cd tests/
                    pytest -v --cov=automechanic .
                    flake8 --exit-zero automechanic
                    pylint --rcfile=../.pylintrc automechanic
workflows:
    version: 2
    build-all:
        jobs:
            - build-ubuntu
